<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->unsignedInteger('proposals_count')
                ->default(0)
                ->after('email')
                ->comment('Tracks total number of proposals generated by the user');

            $table->boolean('is_subscribed')
                ->default(false)
                ->after('proposals_count')
                ->comment('Flag indicating if the user has an active paid Pro subscription');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('users', function (Blueprint $table) {
            $table->dropColumn(['proposals_count', 'is_subscribed']);
        });
    }
};

